#!/usr/bin/env node

'use strict';

const fs = require('fs');
const jade = require('jade');
const ReactDOM = require('react-dom/server');
const React = require('react');

require('babel-register');

main(process.argv[2]);

function main(page) {
  const Page = require(`../pages/${page}.jsx`).default;
  const body = ReactDOM.renderToStaticMarkup(React.createElement(Page, { page }));
  const layout = 'app';
  const template = jade.compileFile(`layouts/${layout}.jade`, {
    basedir: process.cwd(),
    pretty: false,
  });
  fs.writeFileSync(`${page}.html`, template({ body }));
}
